/**
 * EarnRoom branding applied to a generated video.
 *
 * The approved lock-up is NEVER generated by a model. This module produces an
 * explicit, checkable overlay specification — which approved asset goes where,
 * at what size, inside which safe area — so that branding is composited from
 * the real artwork and can then be validated.
 *
 * Pure module: no clock, no network, no file system.
 */
import { brandMisspellings, brandProfile, isApprovedMessage, PRIMARY_TAGLINE } from "./brand";
import type { AspectRatio, PlatformId } from "./types";

export type OverlayLayer =
  | {
      kind: "logo";
      /** Path of the approved artwork in the repository. Never model output. */
      asset: string;
      position: "bottom-right" | "centre";
      /** Fraction of frame width. */
      width: number;
      opacity: number;
      fromSeconds: number;
      toSeconds: number | null;
    }
  | {
      kind: "text";
      role: "tagline" | "website" | "cta" | "caption";
      value: string;
      position: "centre" | "lower-third";
      fromSeconds: number;
      toSeconds: number | null;
    };

export type BrandOverlaySpec = {
  aspect: AspectRatio;
  seconds: number;
  /** Fraction of the frame kept clear of critical text on each edge. */
  safeArea: { top: number; bottom: number; left: number; right: number };
  layers: readonly OverlayLayer[];
};

/**
 * Platform safe areas. Short-form feeds cover the lower third with UI, so the
 * end card text sits above it.
 */
function safeAreaFor(platform: PlatformId): BrandOverlaySpec["safeArea"] {
  switch (platform) {
    case "tiktok":
      return { top: 0.08, bottom: 0.24, left: 0.06, right: 0.16 };
    case "instagram":
    case "youtube_shorts":
      return { top: 0.08, bottom: 0.2, left: 0.06, right: 0.12 };
    case "facebook":
      return { top: 0.06, bottom: 0.16, left: 0.05, right: 0.05 };
    default:
      return { top: 0.05, bottom: 0.1, left: 0.05, right: 0.05 };
  }
}

export function buildBrandOverlay(input: {
  platform: PlatformId;
  aspect: AspectRatio;
  seconds: number;
  tagline: string;
  cta: string;
  /** Subtle corner watermark through the body of the film. */
  watermark?: boolean;
}): BrandOverlaySpec {
  const profile = brandProfile();
  const endCardFrom = Math.max(0, input.seconds - 3);
  const layers: OverlayLayer[] = [];

  if (input.watermark !== false) {
    // The approved wordmark rides the whole film, from the first frame to the
    // end card, so branding survives whichever route rendered the pixels.
    layers.push({
      kind: "logo",
      asset: profile.watermark.asset,
      position: profile.watermark.position,
      width: 0.16,
      opacity: profile.watermark.opacity,
      fromSeconds: 0,
      toSeconds: endCardFrom,
    });
    // The primary campaign tagline is held throughout as well, never left to
    // the end card alone and never left to the generative model to draw.
    layers.push({
      kind: "text",
      role: "tagline",
      value: PRIMARY_TAGLINE,
      position: "lower-third",
      fromSeconds: 0,
      toSeconds: endCardFrom,
    });
  }

  layers.push(
    {
      kind: "logo",
      asset: profile.logoAsset,
      position: "centre",
      width: 0.46,
      opacity: 1,
      fromSeconds: endCardFrom,
      toSeconds: null,
    },
    {
      kind: "text",
      role: "tagline",
      value: input.tagline,
      position: "centre",
      fromSeconds: endCardFrom,
      toSeconds: null,
    },
    {
      kind: "text",
      role: "website",
      value: profile.website,
      position: "centre",
      fromSeconds: endCardFrom,
      toSeconds: null,
    },
    {
      kind: "text",
      role: "cta",
      value: input.cta,
      position: "lower-third",
      fromSeconds: Math.max(0, endCardFrom - 3),
      toSeconds: endCardFrom,
    },
  );

  return {
    aspect: input.aspect,
    seconds: input.seconds,
    safeArea: safeAreaFor(input.platform),
    layers,
  };
}

export type BrandCheckId =
  | "logo_asset"
  | "logo_source"
  | "tagline_approved"
  | "website_present"
  | "cta_present"
  | "brand_spelling"
  | "aspect_ratio"
  | "duration"
  | "safe_area";

export type BrandCheck = { id: BrandCheckId; passed: boolean; detail: string };

export type BrandValidationReport = {
  passed: boolean;
  checks: readonly BrandCheck[];
  failures: readonly string[];
};

/**
 * Validates the branding of a rendered asset. This checks the overlay
 * specification and the rendered file's real properties — it never assumes.
 */
export function validateBranding(input: {
  overlay: BrandOverlaySpec;
  expectedAspect: AspectRatio;
  /** Real properties read back from the rendered file. */
  rendered: { aspect: AspectRatio | null; seconds: number | null } | null;
  copy: { title: string; description: string; caption: string; cta: string };
}): BrandValidationReport {
  const profile = brandProfile();
  const checks: BrandCheck[] = [];
  const logo = input.overlay.layers.find(
    (layer) => layer.kind === "logo" && layer.position === "centre",
  );
  const tagline = input.overlay.layers.find(
    (layer) => layer.kind === "text" && layer.role === "tagline",
  );
  const website = input.overlay.layers.find(
    (layer) => layer.kind === "text" && layer.role === "website",
  );
  const cta = input.overlay.layers.find((layer) => layer.kind === "text" && layer.role === "cta");

  checks.push({
    id: "logo_asset",
    passed: Boolean(logo),
    detail: logo
      ? "End card carries the EarnRoom lock-up."
      : "No EarnRoom lock-up on the end card.",
  });
  checks.push({
    id: "logo_source",
    passed: Boolean(logo && logo.kind === "logo" && logo.asset === profile.logoAsset),
    detail:
      logo && logo.kind === "logo" && logo.asset === profile.logoAsset
        ? "The approved artwork file is used, not a generated logo."
        : "The end card does not reference the approved EarnRoom artwork.",
  });

  const taglineValue = tagline && tagline.kind === "text" ? tagline.value : "";
  checks.push({
    id: "tagline_approved",
    passed: isApprovedMessage(taglineValue),
    detail: isApprovedMessage(taglineValue)
      ? `Approved message: "${taglineValue}".`
      : "The end-card tagline is not on the approved list.",
  });

  const websiteValue = website && website.kind === "text" ? website.value : "";
  checks.push({
    id: "website_present",
    passed: websiteValue === profile.website,
    detail:
      websiteValue === profile.website
        ? `${profile.website} shown on the end card.`
        : "earnroom.co.uk is missing from the end card.",
  });

  const ctaValue = cta && cta.kind === "text" ? cta.value : "";
  checks.push({
    id: "cta_present",
    passed: ctaValue.trim().length > 0 && input.copy.cta.trim().length > 0,
    detail: ctaValue ? `Call to action: "${ctaValue}".` : "No call to action in the asset.",
  });

  const body = `${input.copy.title} ${input.copy.description} ${input.copy.caption}`;
  const wrong = brandMisspellings(body);
  checks.push({
    id: "brand_spelling",
    passed: wrong.length === 0,
    detail: wrong.length
      ? `The brand name is misspelled in the copy as “${wrong[0]}”.`
      : "Brand name spelled EarnRoom.",
  });


  const renderedAspect = input.rendered?.aspect ?? null;
  checks.push({
    id: "aspect_ratio",
    passed: renderedAspect === null ? false : renderedAspect === input.expectedAspect,
    detail:
      renderedAspect === null
        ? "No rendered file to measure yet."
        : renderedAspect === input.expectedAspect
          ? `Rendered ${renderedAspect} as required.`
          : `Rendered ${renderedAspect} but the platform needs ${input.expectedAspect}.`,
  });

  const renderedSeconds = input.rendered?.seconds ?? null;
  checks.push({
    id: "duration",
    passed: renderedSeconds !== null && renderedSeconds > 1,
    detail:
      renderedSeconds === null
        ? "No rendered file to measure yet."
        : `Rendered duration ${renderedSeconds}s.`,
  });

  const safe = input.overlay.safeArea;
  const safeOk = safe.top + safe.bottom < 0.6 && safe.left + safe.right < 0.6;
  checks.push({
    id: "safe_area",
    passed: safeOk,
    detail: safeOk
      ? "End-card text sits inside the platform safe area."
      : "Safe area leaves no room for readable end-card text.",
  });

  const failures = checks.filter((check) => !check.passed).map((check) => check.detail);
  return { passed: failures.length === 0, checks, failures };
}
