/**
 * Browser video soundtrack — the plan, not the sound.
 *
 * The free browser route makes its own audio: a soft procedural music bed, a
 * little room ambience and a handful of sound effects placed on the same
 * timeline as the pictures. Nothing here calls a service, downloads a track or
 * uses a paid voice: it is all generated by the browser itself from this plan.
 *
 * Spoken narration is deliberately absent. A free browser voice is not good
 * enough to publish, so the film carries its story in the picture, the timed
 * text and the music, and says so honestly rather than faking a voice track.
 *
 * Pure module: no Web Audio, no clock, no randomness.
 */
import type { AnimatedScene } from "./types";

/** The sound effects the renderer knows how to synthesise. */
export type AudioCueKind =
  | "roomTone"
  | "footstep"
  | "boxMove"
  | "boxPlace"
  | "phoneOn"
  | "confirm"
  | "doorOpen"
  | "shutter"
  | "riseSwell"
  | "brandResolve";

export type AudioCue = {
  /** Seconds from the start of the whole film. */
  at: number;
  kind: AudioCueKind;
  /** 0..1, relative to the sound effects bus. */
  gain: number;
  /** Which scene asked for it, so the timeline can be checked. */
  scene: number;
};

/** One musical section. The chord is semitone offsets from the section root. */
export type MusicSection = {
  at: number;
  seconds: number;
  /** MIDI note number of the root. */
  root: number;
  chord: readonly number[];
  /** 0..1 — how full and how loud the bed is here. */
  intensity: number;
  /** A soft pulse under the bed. Off in the quietest opening section. */
  pulse: boolean;
  scene: number;
};

export type AmbienceSection = {
  at: number;
  seconds: number;
  /** 0..1 — filtered noise level standing in for room tone. */
  level: number;
};

export type BrowserAudioPlan = {
  seconds: number;
  sampleRate: number;
  music: readonly MusicSection[];
  ambience: readonly AmbienceSection[];
  sfx: readonly AudioCue[];
  /**
   * Always false in the browser: no free voice is good enough to publish, so
   * none is faked. The founder console states this plainly.
   */
  spokenNarration: false;
  /** Bus levels, so the music can never bury an effect. */
  mix: { music: number; ambience: number; sfx: number };
};

export const AUDIO_SAMPLE_RATE = 48_000;

/**
 * A gentle four-chord progression that starts open and unresolved and lands on
 * the tonic at the brand card. Roots are MIDI notes in a comfortable low range.
 */
const PROGRESSION: readonly { root: number; chord: readonly number[] }[] = [
  { root: 45, chord: [0, 7, 12, 15] }, // A minor-ish, open
  { root: 41, chord: [0, 7, 12, 16] }, // F major
  { root: 48, chord: [0, 7, 12, 16] }, // C major
  { root: 43, chord: [0, 7, 12, 14] }, // G suspended
];

/** How loud and how full the bed is for the feeling of the scene. */
function intensityForMood(mood: AnimatedScene["mood"], position: number): number {
  const base =
    mood === "tension" || mood === "doubt"
      ? 0.34
      : mood === "curiosity"
        ? 0.5
        : mood === "hope"
          ? 0.72
          : mood === "relief"
            ? 0.82
            : 0.9;
  // A slow overall build, so the film lifts as it goes rather than sitting flat.
  return Math.min(1, Number((base + position * 0.12).toFixed(3)));
}

/** Sound effects a scene earns from what is actually happening in it. */
function cuesForScene(scene: AnimatedScene, start: number): AudioCue[] {
  const cues: AudioCue[] = [];
  const at = (offset: number) =>
    Number((start + Math.min(Math.max(offset, 0), Math.max(0, scene.seconds - 0.2))).toFixed(3));

  if (scene.role === "endcard") {
    cues.push({ at: at(0.05), kind: "brandResolve", gain: 0.9, scene: scene.index });
    return cues;
  }

  cues.push({ at: at(0.02), kind: "roomTone", gain: 0.35, scene: scene.index });

  for (const member of scene.cast) {
    const offset = member.delay + 0.35;
    switch (member.motion) {
      case "walkIn":
      case "walkOut":
        cues.push({ at: at(offset), kind: "footstep", gain: 0.5, scene: scene.index });
        cues.push({ at: at(offset + 0.42), kind: "footstep", gain: 0.42, scene: scene.index });
        break;
      case "lookAtPhone":
        cues.push({ at: at(offset), kind: "phoneOn", gain: 0.6, scene: scene.index });
        cues.push({ at: at(offset + 0.9), kind: "confirm", gain: 0.45, scene: scene.index });
        break;
      case "pickUp":
        cues.push({ at: at(offset), kind: "boxMove", gain: 0.55, scene: scene.index });
        break;
      case "putDown":
        cues.push({ at: at(offset), kind: "boxPlace", gain: 0.6, scene: scene.index });
        break;
      case "gesture":
      case "point":
        cues.push({ at: at(offset), kind: "shutter", gain: 0.38, scene: scene.index });
        break;
      default:
        break;
    }
    if (member.pose === "openingGarage") {
      cues.push({ at: at(member.delay + 0.2), kind: "doorOpen", gain: 0.62, scene: scene.index });
    }
  }

  if (scene.beat === "discovery" && !cues.some((cue) => cue.kind === "phoneOn")) {
    cues.push({ at: at(0.6), kind: "phoneOn", gain: 0.55, scene: scene.index });
  }
  if (scene.beat === "solution") {
    cues.push({ at: at(0.5), kind: "confirm", gain: 0.5, scene: scene.index });
  }
  if (scene.beat === "outcome") {
    cues.push({ at: at(0.4), kind: "boxPlace", gain: 0.5, scene: scene.index });
    cues.push({ at: at(1.1), kind: "riseSwell", gain: 0.45, scene: scene.index });
  }
  return cues;
}

/**
 * Builds the whole soundtrack from the scenes that were already planned, so a
 * sound can never land on a picture that is not there.
 */
export function buildAudioPlan(
  scenes: readonly AnimatedScene[],
  /** Semitones the whole bed is moved by, so campaigns do not all sound alike. */
  options: { keyOffset?: number } = {},
): BrowserAudioPlan {
  // Two octaves either way at most, so the bed stays in a comfortable range.
  const keyOffset = Math.max(-5, Math.min(5, Math.round(options.keyOffset ?? 0)));
  const music: MusicSection[] = [];
  const ambience: AmbienceSection[] = [];
  const sfx: AudioCue[] = [];

  let cursor = 0;
  scenes.forEach((scene, position) => {
    const share = scenes.length > 1 ? position / (scenes.length - 1) : 1;
    const step = PROGRESSION[position % PROGRESSION.length]!;
    music.push({
      at: Number(cursor.toFixed(3)),
      seconds: Number(scene.seconds.toFixed(3)),
      root: (scene.role === "endcard" ? 48 : step.root) + keyOffset,
      chord: scene.role === "endcard" ? [0, 7, 12, 16, 19] : step.chord,
      intensity: intensityForMood(scene.mood, share),
      pulse: position > 0 && scene.role !== "endcard",
      scene: scene.index,
    });
    if (scene.role !== "endcard") {
      ambience.push({
        at: Number(cursor.toFixed(3)),
        seconds: Number(scene.seconds.toFixed(3)),
        level: scene.environment === "ENV_STREET" ? 0.5 : 0.32,
      });
    }
    sfx.push(...cuesForScene(scene, cursor));
    cursor += scene.seconds;
  });

  return {
    seconds: Number(cursor.toFixed(3)),
    sampleRate: AUDIO_SAMPLE_RATE,
    music,
    ambience,
    sfx,
    spokenNarration: false,
    // Music sits under everything else, so an effect is always audible.
    mix: { music: 0.34, ambience: 0.16, sfx: 0.5 },
  };
}

export type AudioCheck = { passed: boolean; failures: string[] };

/** Checks the soundtrack lines up with the film it belongs to. */
export function validateAudioPlan(plan: BrowserAudioPlan, filmSeconds: number): AudioCheck {
  const failures: string[] = [];
  if (plan.music.length === 0) failures.push("The video has no music.");
  if (plan.sfx.length === 0) failures.push("The video has no sound effects.");
  if (Math.abs(plan.seconds - filmSeconds) > 0.5) {
    failures.push("The soundtrack is not the same length as the film.");
  }
  for (const cue of plan.sfx) {
    if (cue.at < 0 || cue.at > filmSeconds) {
      failures.push("A sound effect is timed outside the film.");
      break;
    }
  }
  let previousEnd = 0;
  for (const section of plan.music) {
    if (section.at + 0.001 < previousEnd) {
      failures.push("Two pieces of music overlap.");
      break;
    }
    previousEnd = section.at + section.seconds;
  }
  if (plan.mix.music > plan.mix.sfx) {
    failures.push("The music is mixed louder than the sound effects.");
  }
  return { passed: failures.length === 0, failures };
}
