/**
 * Browser Local character library.
 *
 * A deliberately small cast of fictional, generic illustrated adults that the
 * story engine reuses across campaigns. Nothing here is generated by a model,
 * downloaded, or licensed: each character is a set of colours plus a layered
 * pose description that the browser renderer draws with plain geometry.
 *
 * The point of the library is continuity — once a campaign picks a character,
 * the same face, hair and clothing appear in every scene of that campaign.
 *
 * Pure module: data and geometry parameters only. No canvas, no clock.
 */

export type CharacterId =
  | "RENTER_CHARACTER_01"
  | "HOST_CHARACTER_01"
  | "NEUTRAL_CHARACTER_01"
  | "SECONDARY_CHARACTER_01";

export type CharacterRole = "renter" | "host" | "neutral" | "secondary";

export type Pose =
  | "standing"
  | "walking"
  | "lookingAround"
  | "worried"
  | "thinking"
  | "holdingBox"
  | "carryingBoxes"
  | "pointing"
  | "lookingAtPhone"
  | "openingGarage"
  | "presenting"
  | "waving"
  | "placingBox"
  | "relieved";

export type Expression =
  | "neutral"
  | "concerned"
  | "confused"
  | "searching"
  | "thinking"
  | "hopeful"
  | "relieved"
  | "happy"
  | "confident";

/** Lightweight deterministic motion primitives. No skeletal animation engine. */
export type CharacterMotion =
  | "idle"
  | "walkIn"
  | "walkOut"
  | "gesture"
  | "point"
  | "lookAround"
  | "lookAtPhone"
  | "pickUp"
  | "putDown"
  | "nod"
  | "smallWave"
  | "relief";

/** Palette for one character. Fixed per character so continuity is automatic. */
export type CharacterDesign = {
  id: CharacterId;
  name: string;
  role: CharacterRole;
  skin: string;
  hair: string;
  hairStyle: "short" | "bob" | "tied";
  top: string;
  sleeve: string;
  trousers: string;
  shoes: string;
  accent: string;
};

/**
 * How the body is arranged for a pose. Angles are radians measured from the
 * shoulder/hip downwards, so 0 is straight down and positive swings forward.
 */
export type PoseSpec = {
  lean: number;
  crouch: number;
  headTilt: number;
  headTurn: number;
  armFar: { shoulder: number; elbow: number };
  armNear: { shoulder: number; elbow: number };
  legFar: number;
  legNear: number;
  /** What the hands are holding, drawn between them where relevant. */
  carry: "none" | "box" | "boxes" | "phone";
  /** Slight vertical offset, used for reaching or setting something down. */
  lift: number;
};

const CHARACTERS: Record<CharacterId, CharacterDesign> = {
  RENTER_CHARACTER_01: {
    id: "RENTER_CHARACTER_01",
    name: "Renter",
    role: "renter",
    skin: "#e8b894",
    hair: "#3b2f2a",
    hairStyle: "short",
    top: "#2f6f8f",
    sleeve: "#2a627e",
    trousers: "#33414d",
    shoes: "#22303a",
    accent: "#f0f4f6",
  },
  HOST_CHARACTER_01: {
    id: "HOST_CHARACTER_01",
    name: "Host",
    role: "host",
    skin: "#c98d63",
    hair: "#20191a",
    hairStyle: "tied",
    top: "#1f7f5f",
    sleeve: "#1a6e52",
    trousers: "#3c4550",
    shoes: "#252d34",
    accent: "#eef6f2",
  },
  NEUTRAL_CHARACTER_01: {
    id: "NEUTRAL_CHARACTER_01",
    name: "Neighbour",
    role: "neutral",
    skin: "#f0c9a8",
    hair: "#7a5230",
    hairStyle: "bob",
    top: "#6a5f8f",
    sleeve: "#5e5480",
    trousers: "#3a3f4a",
    shoes: "#262b31",
    accent: "#f3f1f8",
  },
  SECONDARY_CHARACTER_01: {
    id: "SECONDARY_CHARACTER_01",
    name: "Partner",
    role: "secondary",
    skin: "#8d5c3d",
    hair: "#16110f",
    hairStyle: "short",
    top: "#b8683f",
    sleeve: "#a75c36",
    trousers: "#36404a",
    shoes: "#232a30",
    accent: "#faf0e9",
  },
};

const POSES: Record<Pose, PoseSpec> = {
  standing: {
    lean: 0,
    crouch: 0,
    headTilt: 0,
    headTurn: 0,
    armFar: { shoulder: 0.16, elbow: 0.18 },
    armNear: { shoulder: -0.14, elbow: 0.2 },
    legFar: 0.06,
    legNear: -0.05,
    carry: "none",
    lift: 0,
  },
  walking: {
    lean: 0.05,
    crouch: 0,
    headTilt: 0,
    headTurn: 0.06,
    armFar: { shoulder: 0.5, elbow: 0.3 },
    armNear: { shoulder: -0.45, elbow: 0.3 },
    legFar: 0.42,
    legNear: -0.36,
    carry: "none",
    lift: 0,
  },
  lookingAround: {
    lean: 0,
    crouch: 0,
    headTilt: 0.08,
    headTurn: 0.34,
    armFar: { shoulder: 0.2, elbow: 0.34 },
    armNear: { shoulder: -0.18, elbow: 0.3 },
    legFar: 0.08,
    legNear: -0.07,
    carry: "none",
    lift: 0,
  },
  worried: {
    lean: -0.04,
    crouch: 0.02,
    headTilt: -0.12,
    headTurn: -0.08,
    armFar: { shoulder: 0.34, elbow: 0.9 },
    armNear: { shoulder: -0.3, elbow: 0.86 },
    legFar: 0.05,
    legNear: -0.04,
    carry: "none",
    lift: 0,
  },
  thinking: {
    lean: 0.02,
    crouch: 0,
    headTilt: 0.1,
    headTurn: 0.12,
    armFar: { shoulder: 0.12, elbow: 0.2 },
    armNear: { shoulder: -0.62, elbow: 1.5 },
    legFar: 0.06,
    legNear: -0.05,
    carry: "none",
    lift: 0,
  },
  holdingBox: {
    lean: -0.05,
    crouch: 0.03,
    headTilt: 0,
    headTurn: 0,
    armFar: { shoulder: 0.95, elbow: 0.95 },
    armNear: { shoulder: -0.95, elbow: 0.95 },
    legFar: 0.07,
    legNear: -0.06,
    carry: "box",
    lift: 0,
  },
  carryingBoxes: {
    lean: -0.09,
    crouch: 0.05,
    headTilt: -0.05,
    headTurn: 0,
    armFar: { shoulder: 1.05, elbow: 1.0 },
    armNear: { shoulder: -1.05, elbow: 1.0 },
    legFar: 0.24,
    legNear: -0.2,
    carry: "boxes",
    lift: 0,
  },
  pointing: {
    lean: 0.04,
    crouch: 0,
    headTilt: 0.04,
    headTurn: 0.2,
    armFar: { shoulder: 1.35, elbow: 0.05 },
    armNear: { shoulder: -0.14, elbow: 0.22 },
    legFar: 0.08,
    legNear: -0.07,
    carry: "none",
    lift: 0,
  },
  lookingAtPhone: {
    lean: 0.03,
    crouch: 0,
    headTilt: -0.22,
    headTurn: 0.05,
    armFar: { shoulder: 0.9, elbow: 1.15 },
    armNear: { shoulder: -0.5, elbow: 1.1 },
    legFar: 0.05,
    legNear: -0.05,
    carry: "phone",
    lift: 0,
  },
  openingGarage: {
    lean: 0.06,
    crouch: 0.04,
    headTilt: 0.1,
    headTurn: 0.16,
    armFar: { shoulder: 1.7, elbow: 0.1 },
    armNear: { shoulder: 0.4, elbow: 0.6 },
    legFar: 0.18,
    legNear: -0.12,
    carry: "none",
    lift: 0,
  },
  presenting: {
    lean: 0.02,
    crouch: 0,
    headTilt: 0.05,
    headTurn: 0.18,
    armFar: { shoulder: 1.15, elbow: 0.32 },
    armNear: { shoulder: -0.2, elbow: 0.24 },
    legFar: 0.1,
    legNear: -0.08,
    carry: "none",
    lift: 0,
  },
  waving: {
    lean: 0,
    crouch: 0,
    headTilt: 0.06,
    headTurn: 0.05,
    armFar: { shoulder: 2.15, elbow: 0.35 },
    armNear: { shoulder: -0.16, elbow: 0.22 },
    legFar: 0.07,
    legNear: -0.06,
    carry: "none",
    lift: 0,
  },
  placingBox: {
    lean: -0.14,
    crouch: 0.16,
    headTilt: -0.2,
    headTurn: 0,
    armFar: { shoulder: 1.15, elbow: 0.6 },
    armNear: { shoulder: -1.15, elbow: 0.6 },
    legFar: 0.16,
    legNear: -0.14,
    carry: "box",
    lift: 0.12,
  },
  relieved: {
    lean: -0.02,
    crouch: 0,
    headTilt: 0.16,
    headTurn: 0,
    armFar: { shoulder: 0.24, elbow: 0.5 },
    armNear: { shoulder: -0.24, elbow: 0.5 },
    legFar: 0.06,
    legNear: -0.05,
    carry: "none",
    lift: 0,
  },
};

/** Eyes and mouth for an expression, in head-local units (head radius = 1). */
export type ExpressionSpec = {
  browTilt: number;
  eyeOpen: number;
  eyeLook: number;
  mouthCurve: number;
  mouthWidth: number;
};

const EXPRESSIONS: Record<Expression, ExpressionSpec> = {
  neutral: { browTilt: 0, eyeOpen: 1, eyeLook: 0, mouthCurve: 0, mouthWidth: 0.34 },
  concerned: { browTilt: 0.34, eyeOpen: 0.92, eyeLook: -0.1, mouthCurve: -0.3, mouthWidth: 0.3 },
  confused: { browTilt: -0.3, eyeOpen: 1.05, eyeLook: 0.2, mouthCurve: -0.15, mouthWidth: 0.26 },
  searching: { browTilt: 0.12, eyeOpen: 1.1, eyeLook: 0.34, mouthCurve: -0.05, mouthWidth: 0.28 },
  thinking: { browTilt: 0.2, eyeOpen: 0.86, eyeLook: 0.26, mouthCurve: -0.08, mouthWidth: 0.24 },
  hopeful: { browTilt: -0.12, eyeOpen: 1.08, eyeLook: 0.16, mouthCurve: 0.22, mouthWidth: 0.32 },
  relieved: { browTilt: -0.06, eyeOpen: 0.7, eyeLook: 0, mouthCurve: 0.3, mouthWidth: 0.36 },
  happy: { browTilt: -0.1, eyeOpen: 0.66, eyeLook: 0, mouthCurve: 0.52, mouthWidth: 0.44 },
  confident: { browTilt: -0.05, eyeOpen: 0.96, eyeLook: 0.05, mouthCurve: 0.32, mouthWidth: 0.38 },
};

export const CHARACTER_IDS = Object.keys(CHARACTERS) as CharacterId[];
export const POSE_IDS = Object.keys(POSES) as Pose[];
export const EXPRESSION_IDS = Object.keys(EXPRESSIONS) as Expression[];

export function hasCharacter(id: string): id is CharacterId {
  return Object.prototype.hasOwnProperty.call(CHARACTERS, id);
}

export function character(id: CharacterId): CharacterDesign {
  const found = CHARACTERS[id];
  if (!found) throw new Error(`Unknown character: ${id}`);
  return found;
}

export function pose(id: Pose): PoseSpec {
  return POSES[id] ?? POSES.standing;
}

export function expression(id: Expression): ExpressionSpec {
  return EXPRESSIONS[id] ?? EXPRESSIONS.neutral;
}

export function isPose(value: string): value is Pose {
  return Object.prototype.hasOwnProperty.call(POSES, value);
}

export function isExpression(value: string): value is Expression {
  return Object.prototype.hasOwnProperty.call(EXPRESSIONS, value);
}

/** Registration point, so future artwork can be added without a rewrite. */
export function addCharacter(design: CharacterDesign): void {
  CHARACTERS[design.id] = design;
}

/** The character the story engine should use for a given side of the market. */
export function characterForRole(role: CharacterRole): CharacterId {
  const match = CHARACTER_IDS.find((id) => CHARACTERS[id]!.role === role);
  return match ?? "NEUTRAL_CHARACTER_01";
}
