/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FindStorageRouteImport } from './routes/find-storage'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListSpaceRouteImport } from './routes/list-space'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated.host'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedRenterRouteImport } from './routes/_authenticated.renter'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated.host.index'
import { Route as AuthenticatedHostBookingsRouteImport } from './routes/_authenticated.host.bookings'
import { Route as AuthenticatedHostEarningsRouteImport } from './routes/_authenticated.host.earnings'
import { Route as AuthenticatedHostMessagesRouteImport } from './routes/_authenticated.host.messages'
import { Route as AuthenticatedRenterIndexRouteImport } from './routes/_authenticated.renter.index'
import { Route as AuthenticatedRenterBookingsRouteImport } from './routes/_authenticated.renter.bookings'
import { Route as AuthenticatedRenterMessagesRouteImport } from './routes/_authenticated.renter.messages'
import { Route as AuthenticatedRenterSearchRouteImport } from './routes/_authenticated.renter.search'
import { Route as AuthenticatedHostSpacesIndexRouteImport } from './routes/_authenticated.host.spaces.index'
import { Route as AuthenticatedHostSpacesNewRouteImport } from './routes/_authenticated.host.spaces.new'
import { Route as AuthenticatedHostSpacesSpaceIdEditRouteImport } from './routes/_authenticated.host.spaces.$spaceId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FindStorageRoute = FindStorageRouteImport.update({
  id: '/find-storage',
  path: '/find-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSpaceRoute = ListSpaceRouteImport.update({
  id: '/list-space',
  path: '/list-space',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRenterRoute = AuthenticatedRenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHostRoute,
} as any)
const AuthenticatedHostBookingsRoute =
  AuthenticatedHostBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostEarningsRoute =
  AuthenticatedHostEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostMessagesRoute =
  AuthenticatedHostMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedRenterIndexRoute =
  AuthenticatedRenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterBookingsRoute =
  AuthenticatedRenterBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterMessagesRoute =
  AuthenticatedRenterMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterSearchRoute =
  AuthenticatedRenterSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedHostSpacesIndexRoute =
  AuthenticatedHostSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostSpacesNewRoute =
  AuthenticatedHostSpacesNewRouteImport.update({
    id: '/spaces/new',
    path: '/spaces/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostSpacesSpaceIdEditRoute =
  AuthenticatedHostSpacesSpaceIdEditRouteImport.update({
    id: '/spaces/$spaceId/edit',
    path: '/spaces/$spaceId/edit',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/renter': typeof AuthenticatedRenterRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/host/messages': typeof AuthenticatedHostMessagesRoute
  '/renter/bookings': typeof AuthenticatedRenterBookingsRoute
  '/renter/messages': typeof AuthenticatedRenterMessagesRoute
  '/renter/search': typeof AuthenticatedRenterSearchRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/renter/': typeof AuthenticatedRenterIndexRoute
  '/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/host/spaces/': typeof AuthenticatedHostSpacesIndexRoute
  '/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/host/messages': typeof AuthenticatedHostMessagesRoute
  '/renter/bookings': typeof AuthenticatedRenterBookingsRoute
  '/renter/messages': typeof AuthenticatedRenterMessagesRoute
  '/renter/search': typeof AuthenticatedRenterSearchRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/renter': typeof AuthenticatedRenterIndexRoute
  '/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/host/spaces': typeof AuthenticatedHostSpacesIndexRoute
  '/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/renter': typeof AuthenticatedRenterRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/_authenticated/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/_authenticated/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/_authenticated/host/messages': typeof AuthenticatedHostMessagesRoute
  '/_authenticated/renter/bookings': typeof AuthenticatedRenterBookingsRoute
  '/_authenticated/renter/messages': typeof AuthenticatedRenterMessagesRoute
  '/_authenticated/renter/search': typeof AuthenticatedRenterSearchRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/_authenticated/renter/': typeof AuthenticatedRenterIndexRoute
  '/_authenticated/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/_authenticated/host/spaces/': typeof AuthenticatedHostSpacesIndexRoute
  '/_authenticated/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trust'
    | '/host'
    | '/profile'
    | '/renter'
    | '/spaces/$spaceId'
    | '/host/bookings'
    | '/host/earnings'
    | '/host/messages'
    | '/renter/bookings'
    | '/renter/messages'
    | '/renter/search'
    | '/host/'
    | '/renter/'
    | '/host/spaces/new'
    | '/host/spaces/'
    | '/host/spaces/$spaceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trust'
    | '/profile'
    | '/spaces/$spaceId'
    | '/host/bookings'
    | '/host/earnings'
    | '/host/messages'
    | '/renter/bookings'
    | '/renter/messages'
    | '/renter/search'
    | '/host'
    | '/renter'
    | '/host/spaces/new'
    | '/host/spaces'
    | '/host/spaces/$spaceId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/trust'
    | '/_authenticated/host'
    | '/_authenticated/profile'
    | '/_authenticated/renter'
    | '/spaces/$spaceId'
    | '/_authenticated/host/bookings'
    | '/_authenticated/host/earnings'
    | '/_authenticated/host/messages'
    | '/_authenticated/renter/bookings'
    | '/_authenticated/renter/messages'
    | '/_authenticated/renter/search'
    | '/_authenticated/host/'
    | '/_authenticated/renter/'
    | '/_authenticated/host/spaces/new'
    | '/_authenticated/host/spaces/'
    | '/_authenticated/host/spaces/$spaceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  FindStorageRoute: typeof FindStorageRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListSpaceRoute: typeof ListSpaceRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TrustRoute: typeof TrustRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-storage': {
      id: '/find-storage'
      path: '/find-storage'
      fullPath: '/find-storage'
      preLoaderRoute: typeof FindStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-space': {
      id: '/list-space'
      path: '/list-space'
      fullPath: '/list-space'
      preLoaderRoute: typeof ListSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/renter': {
      id: '/_authenticated/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof AuthenticatedRenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/bookings': {
      id: '/_authenticated/host/bookings'
      path: '/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof AuthenticatedHostBookingsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/earnings': {
      id: '/_authenticated/host/earnings'
      path: '/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof AuthenticatedHostEarningsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/messages': {
      id: '/_authenticated/host/messages'
      path: '/messages'
      fullPath: '/host/messages'
      preLoaderRoute: typeof AuthenticatedHostMessagesRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/renter/': {
      id: '/_authenticated/renter/'
      path: '/'
      fullPath: '/renter/'
      preLoaderRoute: typeof AuthenticatedRenterIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/bookings': {
      id: '/_authenticated/renter/bookings'
      path: '/bookings'
      fullPath: '/renter/bookings'
      preLoaderRoute: typeof AuthenticatedRenterBookingsRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/messages': {
      id: '/_authenticated/renter/messages'
      path: '/messages'
      fullPath: '/renter/messages'
      preLoaderRoute: typeof AuthenticatedRenterMessagesRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/search': {
      id: '/_authenticated/renter/search'
      path: '/search'
      fullPath: '/renter/search'
      preLoaderRoute: typeof AuthenticatedRenterSearchRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/host/spaces/': {
      id: '/_authenticated/host/spaces/'
      path: '/spaces'
      fullPath: '/host/spaces/'
      preLoaderRoute: typeof AuthenticatedHostSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/spaces/new': {
      id: '/_authenticated/host/spaces/new'
      path: '/spaces/new'
      fullPath: '/host/spaces/new'
      preLoaderRoute: typeof AuthenticatedHostSpacesNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/spaces/$spaceId/edit': {
      id: '/_authenticated/host/spaces/$spaceId/edit'
      path: '/spaces/$spaceId/edit'
      fullPath: '/host/spaces/$spaceId/edit'
      preLoaderRoute: typeof AuthenticatedHostSpacesSpaceIdEditRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
  }
}

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostBookingsRoute: typeof AuthenticatedHostBookingsRoute
  AuthenticatedHostEarningsRoute: typeof AuthenticatedHostEarningsRoute
  AuthenticatedHostMessagesRoute: typeof AuthenticatedHostMessagesRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
  AuthenticatedHostSpacesNewRoute: typeof AuthenticatedHostSpacesNewRoute
  AuthenticatedHostSpacesIndexRoute: typeof AuthenticatedHostSpacesIndexRoute
  AuthenticatedHostSpacesSpaceIdEditRoute: typeof AuthenticatedHostSpacesSpaceIdEditRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostBookingsRoute: AuthenticatedHostBookingsRoute,
  AuthenticatedHostEarningsRoute: AuthenticatedHostEarningsRoute,
  AuthenticatedHostMessagesRoute: AuthenticatedHostMessagesRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
  AuthenticatedHostSpacesNewRoute: AuthenticatedHostSpacesNewRoute,
  AuthenticatedHostSpacesIndexRoute: AuthenticatedHostSpacesIndexRoute,
  AuthenticatedHostSpacesSpaceIdEditRoute:
    AuthenticatedHostSpacesSpaceIdEditRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRenterRouteChildren {
  AuthenticatedRenterBookingsRoute: typeof AuthenticatedRenterBookingsRoute
  AuthenticatedRenterMessagesRoute: typeof AuthenticatedRenterMessagesRoute
  AuthenticatedRenterSearchRoute: typeof AuthenticatedRenterSearchRoute
  AuthenticatedRenterIndexRoute: typeof AuthenticatedRenterIndexRoute
}

const AuthenticatedRenterRouteChildren: AuthenticatedRenterRouteChildren = {
  AuthenticatedRenterBookingsRoute: AuthenticatedRenterBookingsRoute,
  AuthenticatedRenterMessagesRoute: AuthenticatedRenterMessagesRoute,
  AuthenticatedRenterSearchRoute: AuthenticatedRenterSearchRoute,
  AuthenticatedRenterIndexRoute: AuthenticatedRenterIndexRoute,
}

const AuthenticatedRenterRouteWithChildren =
  AuthenticatedRenterRoute._addFileChildren(AuthenticatedRenterRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRenterRoute: typeof AuthenticatedRenterRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRenterRoute: AuthenticatedRenterRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  FindStorageRoute: FindStorageRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListSpaceRoute: ListSpaceRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TrustRoute: TrustRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
