/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as FindStorageRouteImport } from './routes/find-storage'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListSpaceRouteImport } from './routes/list-space'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated.host'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedRenterRouteImport } from './routes/_authenticated.renter'
import { Route as SpacesSpaceIdRouteImport } from './routes/spaces.$spaceId'
import { Route as AuthenticatedHostIndexRouteImport } from './routes/_authenticated.host.index'
import { Route as AuthenticatedHostBookingsRouteImport } from './routes/_authenticated.host.bookings'
import { Route as AuthenticatedHostEarningsRouteImport } from './routes/_authenticated.host.earnings'
import { Route as AuthenticatedRenterIndexRouteImport } from './routes/_authenticated.renter.index'
import { Route as AuthenticatedRenterMatchesRouteImport } from './routes/_authenticated.renter.matches'
import { Route as AuthenticatedRenterSearchRouteImport } from './routes/_authenticated.renter.search'
import { Route as AuthenticatedAdminReviewsIndexRouteImport } from './routes/_authenticated.admin.reviews.index'
import { Route as AuthenticatedAdminSupportIndexRouteImport } from './routes/_authenticated.admin.support.index'
import { Route as AuthenticatedAdminSupportCaseIdRouteImport } from './routes/_authenticated.admin.support.$caseId'
import { Route as AuthenticatedHostMessagesIndexRouteImport } from './routes/_authenticated.host.messages.index'
import { Route as AuthenticatedHostMessagesBookingIdRouteImport } from './routes/_authenticated.host.messages.$bookingId'
import { Route as AuthenticatedHostPayoutsRefreshRouteImport } from './routes/_authenticated.host.payouts.refresh'
import { Route as AuthenticatedHostPayoutsReturnRouteImport } from './routes/_authenticated.host.payouts.return'
import { Route as AuthenticatedHostRequestsRequestIdRouteImport } from './routes/_authenticated.host.requests.$requestId'
import { Route as AuthenticatedHostSpacesIndexRouteImport } from './routes/_authenticated.host.spaces.index'
import { Route as AuthenticatedHostSpacesNewRouteImport } from './routes/_authenticated.host.spaces.new'
import { Route as AuthenticatedRenterBookingsIndexRouteImport } from './routes/_authenticated.renter.bookings.index'
import { Route as AuthenticatedRenterBookingsBookingIdRouteImport } from './routes/_authenticated.renter.bookings.$bookingId'
import { Route as AuthenticatedRenterInventoryIndexRouteImport } from './routes/_authenticated.renter.inventory.index'
import { Route as AuthenticatedRenterInventoryAddRouteImport } from './routes/_authenticated.renter.inventory.add'
import { Route as AuthenticatedRenterInventoryPhotosRouteImport } from './routes/_authenticated.renter.inventory.photos'
import { Route as AuthenticatedRenterInventoryReviewRouteImport } from './routes/_authenticated.renter.inventory.review'
import { Route as AuthenticatedRenterMessagesIndexRouteImport } from './routes/_authenticated.renter.messages.index'
import { Route as AuthenticatedRenterMessagesBookingIdRouteImport } from './routes/_authenticated.renter.messages.$bookingId'
import { Route as AuthenticatedRenterPaymentsReturnRouteImport } from './routes/_authenticated.renter.payments.return'
import { Route as AuthenticatedRenterRequestsIndexRouteImport } from './routes/_authenticated.renter.requests.index'
import { Route as AuthenticatedRenterRequestsRequestIdRouteImport } from './routes/_authenticated.renter.requests.$requestId'
import { Route as AuthenticatedRenterRequestsNewRouteImport } from './routes/_authenticated.renter.requests.new'
import { Route as AuthenticatedSupportCasesCaseIdRouteImport } from './routes/_authenticated.support.cases.$caseId'
import { Route as ApiPublicPayoutsReleaseRouteImport } from './routes/api/public/payouts/release'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as AuthenticatedHostSpacesSpaceIdEditRouteImport } from './routes/_authenticated.host.spaces.$spaceId.edit'
import { Route as AuthenticatedRenterRequestsRequestIdIndexRouteImport } from './routes/_authenticated.renter.requests.$requestId.index'
import { Route as AuthenticatedRenterRequestsRequestIdBookingRouteImport } from './routes/_authenticated.renter.requests.$requestId.booking'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const FindStorageRoute = FindStorageRouteImport.update({
  id: '/find-storage',
  path: '/find-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSpaceRoute = ListSpaceRouteImport.update({
  id: '/list-space',
  path: '/list-space',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRenterRoute = AuthenticatedRenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SpacesSpaceIdRoute = SpacesSpaceIdRouteImport.update({
  id: '/spaces/$spaceId',
  path: '/spaces/$spaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostIndexRoute = AuthenticatedHostIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedHostRoute,
} as any)
const AuthenticatedHostBookingsRoute =
  AuthenticatedHostBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostEarningsRoute =
  AuthenticatedHostEarningsRouteImport.update({
    id: '/earnings',
    path: '/earnings',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedRenterIndexRoute =
  AuthenticatedRenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterMatchesRoute =
  AuthenticatedRenterMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterSearchRoute =
  AuthenticatedRenterSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedAdminReviewsIndexRoute =
  AuthenticatedAdminReviewsIndexRouteImport.update({
    id: '/admin/reviews/',
    path: '/admin/reviews/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportIndexRoute =
  AuthenticatedAdminSupportIndexRouteImport.update({
    id: '/admin/support/',
    path: '/admin/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportCaseIdRoute =
  AuthenticatedAdminSupportCaseIdRouteImport.update({
    id: '/admin/support/$caseId',
    path: '/admin/support/$caseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHostMessagesIndexRoute =
  AuthenticatedHostMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostMessagesBookingIdRoute =
  AuthenticatedHostMessagesBookingIdRouteImport.update({
    id: '/messages/$bookingId',
    path: '/messages/$bookingId',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostPayoutsRefreshRoute =
  AuthenticatedHostPayoutsRefreshRouteImport.update({
    id: '/payouts/refresh',
    path: '/payouts/refresh',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostPayoutsReturnRoute =
  AuthenticatedHostPayoutsReturnRouteImport.update({
    id: '/payouts/return',
    path: '/payouts/return',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostRequestsRequestIdRoute =
  AuthenticatedHostRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostSpacesIndexRoute =
  AuthenticatedHostSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedHostSpacesNewRoute =
  AuthenticatedHostSpacesNewRouteImport.update({
    id: '/spaces/new',
    path: '/spaces/new',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedRenterBookingsIndexRoute =
  AuthenticatedRenterBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterBookingsBookingIdRoute =
  AuthenticatedRenterBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterInventoryIndexRoute =
  AuthenticatedRenterInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterInventoryAddRoute =
  AuthenticatedRenterInventoryAddRouteImport.update({
    id: '/inventory/add',
    path: '/inventory/add',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterInventoryPhotosRoute =
  AuthenticatedRenterInventoryPhotosRouteImport.update({
    id: '/inventory/photos',
    path: '/inventory/photos',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterInventoryReviewRoute =
  AuthenticatedRenterInventoryReviewRouteImport.update({
    id: '/inventory/review',
    path: '/inventory/review',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterMessagesIndexRoute =
  AuthenticatedRenterMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterMessagesBookingIdRoute =
  AuthenticatedRenterMessagesBookingIdRouteImport.update({
    id: '/messages/$bookingId',
    path: '/messages/$bookingId',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterPaymentsReturnRoute =
  AuthenticatedRenterPaymentsReturnRouteImport.update({
    id: '/payments/return',
    path: '/payments/return',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterRequestsIndexRoute =
  AuthenticatedRenterRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterRequestsRequestIdRoute =
  AuthenticatedRenterRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedRenterRequestsNewRoute =
  AuthenticatedRenterRequestsNewRouteImport.update({
    id: '/requests/new',
    path: '/requests/new',
    getParentRoute: () => AuthenticatedRenterRoute,
  } as any)
const AuthenticatedSupportCasesCaseIdRoute =
  AuthenticatedSupportCasesCaseIdRouteImport.update({
    id: '/support/cases/$caseId',
    path: '/support/cases/$caseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPayoutsReleaseRoute = ApiPublicPayoutsReleaseRouteImport.update({
  id: '/api/public/payouts/release',
  path: '/api/public/payouts/release',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHostSpacesSpaceIdEditRoute =
  AuthenticatedHostSpacesSpaceIdEditRouteImport.update({
    id: '/spaces/$spaceId/edit',
    path: '/spaces/$spaceId/edit',
    getParentRoute: () => AuthenticatedHostRoute,
  } as any)
const AuthenticatedRenterRequestsRequestIdIndexRoute =
  AuthenticatedRenterRequestsRequestIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRenterRequestsRequestIdRoute,
  } as any)
const AuthenticatedRenterRequestsRequestIdBookingRoute =
  AuthenticatedRenterRequestsRequestIdBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedRenterRequestsRequestIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/host': typeof AuthenticatedHostRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/renter': typeof AuthenticatedRenterRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/renter/matches': typeof AuthenticatedRenterMatchesRoute
  '/renter/search': typeof AuthenticatedRenterSearchRoute
  '/host/': typeof AuthenticatedHostIndexRoute
  '/renter/': typeof AuthenticatedRenterIndexRoute
  '/admin/support/$caseId': typeof AuthenticatedAdminSupportCaseIdRoute
  '/host/messages/$bookingId': typeof AuthenticatedHostMessagesBookingIdRoute
  '/host/payouts/refresh': typeof AuthenticatedHostPayoutsRefreshRoute
  '/host/payouts/return': typeof AuthenticatedHostPayoutsReturnRoute
  '/host/requests/$requestId': typeof AuthenticatedHostRequestsRequestIdRoute
  '/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/renter/bookings/$bookingId': typeof AuthenticatedRenterBookingsBookingIdRoute
  '/renter/inventory/add': typeof AuthenticatedRenterInventoryAddRoute
  '/renter/inventory/photos': typeof AuthenticatedRenterInventoryPhotosRoute
  '/renter/inventory/review': typeof AuthenticatedRenterInventoryReviewRoute
  '/renter/messages/$bookingId': typeof AuthenticatedRenterMessagesBookingIdRoute
  '/renter/payments/return': typeof AuthenticatedRenterPaymentsReturnRoute
  '/renter/requests/$requestId': typeof AuthenticatedRenterRequestsRequestIdRouteWithChildren
  '/renter/requests/new': typeof AuthenticatedRenterRequestsNewRoute
  '/support/cases/$caseId': typeof AuthenticatedSupportCasesCaseIdRoute
  '/api/public/payouts/release': typeof ApiPublicPayoutsReleaseRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/reviews/': typeof AuthenticatedAdminReviewsIndexRoute
  '/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/host/messages/': typeof AuthenticatedHostMessagesIndexRoute
  '/host/spaces/': typeof AuthenticatedHostSpacesIndexRoute
  '/renter/bookings/': typeof AuthenticatedRenterBookingsIndexRoute
  '/renter/inventory/': typeof AuthenticatedRenterInventoryIndexRoute
  '/renter/messages/': typeof AuthenticatedRenterMessagesIndexRoute
  '/renter/requests/': typeof AuthenticatedRenterRequestsIndexRoute
  '/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
  '/renter/requests/$requestId/booking': typeof AuthenticatedRenterRequestsRequestIdBookingRoute
  '/renter/requests/$requestId/': typeof AuthenticatedRenterRequestsRequestIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/renter/matches': typeof AuthenticatedRenterMatchesRoute
  '/renter/search': typeof AuthenticatedRenterSearchRoute
  '/host': typeof AuthenticatedHostIndexRoute
  '/renter': typeof AuthenticatedRenterIndexRoute
  '/admin/support/$caseId': typeof AuthenticatedAdminSupportCaseIdRoute
  '/host/messages/$bookingId': typeof AuthenticatedHostMessagesBookingIdRoute
  '/host/payouts/refresh': typeof AuthenticatedHostPayoutsRefreshRoute
  '/host/payouts/return': typeof AuthenticatedHostPayoutsReturnRoute
  '/host/requests/$requestId': typeof AuthenticatedHostRequestsRequestIdRoute
  '/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/renter/bookings/$bookingId': typeof AuthenticatedRenterBookingsBookingIdRoute
  '/renter/inventory/add': typeof AuthenticatedRenterInventoryAddRoute
  '/renter/inventory/photos': typeof AuthenticatedRenterInventoryPhotosRoute
  '/renter/inventory/review': typeof AuthenticatedRenterInventoryReviewRoute
  '/renter/messages/$bookingId': typeof AuthenticatedRenterMessagesBookingIdRoute
  '/renter/payments/return': typeof AuthenticatedRenterPaymentsReturnRoute
  '/renter/requests/new': typeof AuthenticatedRenterRequestsNewRoute
  '/support/cases/$caseId': typeof AuthenticatedSupportCasesCaseIdRoute
  '/api/public/payouts/release': typeof ApiPublicPayoutsReleaseRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsIndexRoute
  '/admin/support': typeof AuthenticatedAdminSupportIndexRoute
  '/host/messages': typeof AuthenticatedHostMessagesIndexRoute
  '/host/spaces': typeof AuthenticatedHostSpacesIndexRoute
  '/renter/bookings': typeof AuthenticatedRenterBookingsIndexRoute
  '/renter/inventory': typeof AuthenticatedRenterInventoryIndexRoute
  '/renter/messages': typeof AuthenticatedRenterMessagesIndexRoute
  '/renter/requests': typeof AuthenticatedRenterRequestsIndexRoute
  '/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
  '/renter/requests/$requestId/booking': typeof AuthenticatedRenterRequestsRequestIdBookingRoute
  '/renter/requests/$requestId': typeof AuthenticatedRenterRequestsRequestIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/find-storage': typeof FindStorageRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/get-started': typeof GetStartedRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-space': typeof ListSpaceRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/trust': typeof TrustRoute
  '/_authenticated/host': typeof AuthenticatedHostRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/renter': typeof AuthenticatedRenterRouteWithChildren
  '/spaces/$spaceId': typeof SpacesSpaceIdRoute
  '/_authenticated/host/bookings': typeof AuthenticatedHostBookingsRoute
  '/_authenticated/host/earnings': typeof AuthenticatedHostEarningsRoute
  '/_authenticated/renter/matches': typeof AuthenticatedRenterMatchesRoute
  '/_authenticated/renter/search': typeof AuthenticatedRenterSearchRoute
  '/_authenticated/host/': typeof AuthenticatedHostIndexRoute
  '/_authenticated/renter/': typeof AuthenticatedRenterIndexRoute
  '/_authenticated/admin/support/$caseId': typeof AuthenticatedAdminSupportCaseIdRoute
  '/_authenticated/host/messages/$bookingId': typeof AuthenticatedHostMessagesBookingIdRoute
  '/_authenticated/host/payouts/refresh': typeof AuthenticatedHostPayoutsRefreshRoute
  '/_authenticated/host/payouts/return': typeof AuthenticatedHostPayoutsReturnRoute
  '/_authenticated/host/requests/$requestId': typeof AuthenticatedHostRequestsRequestIdRoute
  '/_authenticated/host/spaces/new': typeof AuthenticatedHostSpacesNewRoute
  '/_authenticated/renter/bookings/$bookingId': typeof AuthenticatedRenterBookingsBookingIdRoute
  '/_authenticated/renter/inventory/add': typeof AuthenticatedRenterInventoryAddRoute
  '/_authenticated/renter/inventory/photos': typeof AuthenticatedRenterInventoryPhotosRoute
  '/_authenticated/renter/inventory/review': typeof AuthenticatedRenterInventoryReviewRoute
  '/_authenticated/renter/messages/$bookingId': typeof AuthenticatedRenterMessagesBookingIdRoute
  '/_authenticated/renter/payments/return': typeof AuthenticatedRenterPaymentsReturnRoute
  '/_authenticated/renter/requests/$requestId': typeof AuthenticatedRenterRequestsRequestIdRouteWithChildren
  '/_authenticated/renter/requests/new': typeof AuthenticatedRenterRequestsNewRoute
  '/_authenticated/support/cases/$caseId': typeof AuthenticatedSupportCasesCaseIdRoute
  '/api/public/payouts/release': typeof ApiPublicPayoutsReleaseRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/reviews/': typeof AuthenticatedAdminReviewsIndexRoute
  '/_authenticated/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/_authenticated/host/messages/': typeof AuthenticatedHostMessagesIndexRoute
  '/_authenticated/host/spaces/': typeof AuthenticatedHostSpacesIndexRoute
  '/_authenticated/renter/bookings/': typeof AuthenticatedRenterBookingsIndexRoute
  '/_authenticated/renter/inventory/': typeof AuthenticatedRenterInventoryIndexRoute
  '/_authenticated/renter/messages/': typeof AuthenticatedRenterMessagesIndexRoute
  '/_authenticated/renter/requests/': typeof AuthenticatedRenterRequestsIndexRoute
  '/_authenticated/host/spaces/$spaceId/edit': typeof AuthenticatedHostSpacesSpaceIdEditRoute
  '/_authenticated/renter/requests/$requestId/booking': typeof AuthenticatedRenterRequestsRequestIdBookingRoute
  '/_authenticated/renter/requests/$requestId/': typeof AuthenticatedRenterRequestsRequestIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/trust'
    | '/host'
    | '/profile'
    | '/renter'
    | '/spaces/$spaceId'
    | '/host/bookings'
    | '/host/earnings'
    | '/renter/matches'
    | '/renter/search'
    | '/host/'
    | '/renter/'
    | '/admin/support/$caseId'
    | '/host/messages/$bookingId'
    | '/host/payouts/refresh'
    | '/host/payouts/return'
    | '/host/requests/$requestId'
    | '/host/spaces/new'
    | '/renter/bookings/$bookingId'
    | '/renter/inventory/add'
    | '/renter/inventory/photos'
    | '/renter/inventory/review'
    | '/renter/messages/$bookingId'
    | '/renter/payments/return'
    | '/renter/requests/$requestId'
    | '/renter/requests/new'
    | '/support/cases/$caseId'
    | '/api/public/payouts/release'
    | '/api/public/stripe/webhook'
    | '/admin/reviews/'
    | '/admin/support/'
    | '/host/messages/'
    | '/host/spaces/'
    | '/renter/bookings/'
    | '/renter/inventory/'
    | '/renter/messages/'
    | '/renter/requests/'
    | '/host/spaces/$spaceId/edit'
    | '/renter/requests/$requestId/booking'
    | '/renter/requests/$requestId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/trust'
    | '/profile'
    | '/spaces/$spaceId'
    | '/host/bookings'
    | '/host/earnings'
    | '/renter/matches'
    | '/renter/search'
    | '/host'
    | '/renter'
    | '/admin/support/$caseId'
    | '/host/messages/$bookingId'
    | '/host/payouts/refresh'
    | '/host/payouts/return'
    | '/host/requests/$requestId'
    | '/host/spaces/new'
    | '/renter/bookings/$bookingId'
    | '/renter/inventory/add'
    | '/renter/inventory/photos'
    | '/renter/inventory/review'
    | '/renter/messages/$bookingId'
    | '/renter/payments/return'
    | '/renter/requests/new'
    | '/support/cases/$caseId'
    | '/api/public/payouts/release'
    | '/api/public/stripe/webhook'
    | '/admin/reviews'
    | '/admin/support'
    | '/host/messages'
    | '/host/spaces'
    | '/renter/bookings'
    | '/renter/inventory'
    | '/renter/messages'
    | '/renter/requests'
    | '/host/spaces/$spaceId/edit'
    | '/renter/requests/$requestId/booking'
    | '/renter/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/design-system'
    | '/find-storage'
    | '/forgot-password'
    | '/get-started'
    | '/how-it-works'
    | '/list-space'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/trust'
    | '/_authenticated/host'
    | '/_authenticated/profile'
    | '/_authenticated/renter'
    | '/spaces/$spaceId'
    | '/_authenticated/host/bookings'
    | '/_authenticated/host/earnings'
    | '/_authenticated/renter/matches'
    | '/_authenticated/renter/search'
    | '/_authenticated/host/'
    | '/_authenticated/renter/'
    | '/_authenticated/admin/support/$caseId'
    | '/_authenticated/host/messages/$bookingId'
    | '/_authenticated/host/payouts/refresh'
    | '/_authenticated/host/payouts/return'
    | '/_authenticated/host/requests/$requestId'
    | '/_authenticated/host/spaces/new'
    | '/_authenticated/renter/bookings/$bookingId'
    | '/_authenticated/renter/inventory/add'
    | '/_authenticated/renter/inventory/photos'
    | '/_authenticated/renter/inventory/review'
    | '/_authenticated/renter/messages/$bookingId'
    | '/_authenticated/renter/payments/return'
    | '/_authenticated/renter/requests/$requestId'
    | '/_authenticated/renter/requests/new'
    | '/_authenticated/support/cases/$caseId'
    | '/api/public/payouts/release'
    | '/api/public/stripe/webhook'
    | '/_authenticated/admin/reviews/'
    | '/_authenticated/admin/support/'
    | '/_authenticated/host/messages/'
    | '/_authenticated/host/spaces/'
    | '/_authenticated/renter/bookings/'
    | '/_authenticated/renter/inventory/'
    | '/_authenticated/renter/messages/'
    | '/_authenticated/renter/requests/'
    | '/_authenticated/host/spaces/$spaceId/edit'
    | '/_authenticated/renter/requests/$requestId/booking'
    | '/_authenticated/renter/requests/$requestId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  FindStorageRoute: typeof FindStorageRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GetStartedRoute: typeof GetStartedRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListSpaceRoute: typeof ListSpaceRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TrustRoute: typeof TrustRoute
  SpacesSpaceIdRoute: typeof SpacesSpaceIdRoute
  ApiPublicPayoutsReleaseRoute: typeof ApiPublicPayoutsReleaseRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-storage': {
      id: '/find-storage'
      path: '/find-storage'
      fullPath: '/find-storage'
      preLoaderRoute: typeof FindStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-space': {
      id: '/list-space'
      path: '/list-space'
      fullPath: '/list-space'
      preLoaderRoute: typeof ListSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/renter': {
      id: '/_authenticated/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof AuthenticatedRenterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/spaces/$spaceId': {
      id: '/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/spaces/$spaceId'
      preLoaderRoute: typeof SpacesSpaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/': {
      id: '/_authenticated/host/'
      path: '/'
      fullPath: '/host/'
      preLoaderRoute: typeof AuthenticatedHostIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/bookings': {
      id: '/_authenticated/host/bookings'
      path: '/bookings'
      fullPath: '/host/bookings'
      preLoaderRoute: typeof AuthenticatedHostBookingsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/earnings': {
      id: '/_authenticated/host/earnings'
      path: '/earnings'
      fullPath: '/host/earnings'
      preLoaderRoute: typeof AuthenticatedHostEarningsRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/renter/': {
      id: '/_authenticated/renter/'
      path: '/'
      fullPath: '/renter/'
      preLoaderRoute: typeof AuthenticatedRenterIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/matches': {
      id: '/_authenticated/renter/matches'
      path: '/matches'
      fullPath: '/renter/matches'
      preLoaderRoute: typeof AuthenticatedRenterMatchesRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/search': {
      id: '/_authenticated/renter/search'
      path: '/search'
      fullPath: '/renter/search'
      preLoaderRoute: typeof AuthenticatedRenterSearchRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/admin/reviews/': {
      id: '/_authenticated/admin/reviews/'
      path: '/admin/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AuthenticatedAdminReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support/': {
      id: '/_authenticated/admin/support/'
      path: '/admin/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AuthenticatedAdminSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support/$caseId': {
      id: '/_authenticated/admin/support/$caseId'
      path: '/admin/support/$caseId'
      fullPath: '/admin/support/$caseId'
      preLoaderRoute: typeof AuthenticatedAdminSupportCaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/host/messages/': {
      id: '/_authenticated/host/messages/'
      path: '/messages'
      fullPath: '/host/messages/'
      preLoaderRoute: typeof AuthenticatedHostMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/messages/$bookingId': {
      id: '/_authenticated/host/messages/$bookingId'
      path: '/messages/$bookingId'
      fullPath: '/host/messages/$bookingId'
      preLoaderRoute: typeof AuthenticatedHostMessagesBookingIdRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/payouts/refresh': {
      id: '/_authenticated/host/payouts/refresh'
      path: '/payouts/refresh'
      fullPath: '/host/payouts/refresh'
      preLoaderRoute: typeof AuthenticatedHostPayoutsRefreshRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/payouts/return': {
      id: '/_authenticated/host/payouts/return'
      path: '/payouts/return'
      fullPath: '/host/payouts/return'
      preLoaderRoute: typeof AuthenticatedHostPayoutsReturnRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/requests/$requestId': {
      id: '/_authenticated/host/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/host/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedHostRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/spaces/': {
      id: '/_authenticated/host/spaces/'
      path: '/spaces'
      fullPath: '/host/spaces/'
      preLoaderRoute: typeof AuthenticatedHostSpacesIndexRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/host/spaces/new': {
      id: '/_authenticated/host/spaces/new'
      path: '/spaces/new'
      fullPath: '/host/spaces/new'
      preLoaderRoute: typeof AuthenticatedHostSpacesNewRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/renter/bookings/': {
      id: '/_authenticated/renter/bookings/'
      path: '/bookings'
      fullPath: '/renter/bookings/'
      preLoaderRoute: typeof AuthenticatedRenterBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/bookings/$bookingId': {
      id: '/_authenticated/renter/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/renter/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedRenterBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/inventory/': {
      id: '/_authenticated/renter/inventory/'
      path: '/inventory'
      fullPath: '/renter/inventory/'
      preLoaderRoute: typeof AuthenticatedRenterInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/inventory/add': {
      id: '/_authenticated/renter/inventory/add'
      path: '/inventory/add'
      fullPath: '/renter/inventory/add'
      preLoaderRoute: typeof AuthenticatedRenterInventoryAddRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/inventory/photos': {
      id: '/_authenticated/renter/inventory/photos'
      path: '/inventory/photos'
      fullPath: '/renter/inventory/photos'
      preLoaderRoute: typeof AuthenticatedRenterInventoryPhotosRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/inventory/review': {
      id: '/_authenticated/renter/inventory/review'
      path: '/inventory/review'
      fullPath: '/renter/inventory/review'
      preLoaderRoute: typeof AuthenticatedRenterInventoryReviewRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/messages/': {
      id: '/_authenticated/renter/messages/'
      path: '/messages'
      fullPath: '/renter/messages/'
      preLoaderRoute: typeof AuthenticatedRenterMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/messages/$bookingId': {
      id: '/_authenticated/renter/messages/$bookingId'
      path: '/messages/$bookingId'
      fullPath: '/renter/messages/$bookingId'
      preLoaderRoute: typeof AuthenticatedRenterMessagesBookingIdRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/payments/return': {
      id: '/_authenticated/renter/payments/return'
      path: '/payments/return'
      fullPath: '/renter/payments/return'
      preLoaderRoute: typeof AuthenticatedRenterPaymentsReturnRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/requests/': {
      id: '/_authenticated/renter/requests/'
      path: '/requests'
      fullPath: '/renter/requests/'
      preLoaderRoute: typeof AuthenticatedRenterRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/requests/$requestId': {
      id: '/_authenticated/renter/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/renter/requests/$requestId'
      preLoaderRoute: typeof AuthenticatedRenterRequestsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/renter/requests/new': {
      id: '/_authenticated/renter/requests/new'
      path: '/requests/new'
      fullPath: '/renter/requests/new'
      preLoaderRoute: typeof AuthenticatedRenterRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRenterRoute
    }
    '/_authenticated/support/cases/$caseId': {
      id: '/_authenticated/support/cases/$caseId'
      path: '/support/cases/$caseId'
      fullPath: '/support/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedSupportCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payouts/release': {
      id: '/api/public/payouts/release'
      path: '/api/public/payouts/release'
      fullPath: '/api/public/payouts/release'
      preLoaderRoute: typeof ApiPublicPayoutsReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/host/spaces/$spaceId/edit': {
      id: '/_authenticated/host/spaces/$spaceId/edit'
      path: '/spaces/$spaceId/edit'
      fullPath: '/host/spaces/$spaceId/edit'
      preLoaderRoute: typeof AuthenticatedHostSpacesSpaceIdEditRouteImport
      parentRoute: typeof AuthenticatedHostRoute
    }
    '/_authenticated/renter/requests/$requestId/': {
      id: '/_authenticated/renter/requests/$requestId/'
      path: '/'
      fullPath: '/renter/requests/$requestId/'
      preLoaderRoute: typeof AuthenticatedRenterRequestsRequestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRenterRequestsRequestIdRoute
    }
    '/_authenticated/renter/requests/$requestId/booking': {
      id: '/_authenticated/renter/requests/$requestId/booking'
      path: '/booking'
      fullPath: '/renter/requests/$requestId/booking'
      preLoaderRoute: typeof AuthenticatedRenterRequestsRequestIdBookingRouteImport
      parentRoute: typeof AuthenticatedRenterRequestsRequestIdRoute
    }
  }
}

interface AuthenticatedHostRouteChildren {
  AuthenticatedHostBookingsRoute: typeof AuthenticatedHostBookingsRoute
  AuthenticatedHostEarningsRoute: typeof AuthenticatedHostEarningsRoute
  AuthenticatedHostIndexRoute: typeof AuthenticatedHostIndexRoute
  AuthenticatedHostMessagesBookingIdRoute: typeof AuthenticatedHostMessagesBookingIdRoute
  AuthenticatedHostPayoutsRefreshRoute: typeof AuthenticatedHostPayoutsRefreshRoute
  AuthenticatedHostPayoutsReturnRoute: typeof AuthenticatedHostPayoutsReturnRoute
  AuthenticatedHostRequestsRequestIdRoute: typeof AuthenticatedHostRequestsRequestIdRoute
  AuthenticatedHostSpacesNewRoute: typeof AuthenticatedHostSpacesNewRoute
  AuthenticatedHostMessagesIndexRoute: typeof AuthenticatedHostMessagesIndexRoute
  AuthenticatedHostSpacesIndexRoute: typeof AuthenticatedHostSpacesIndexRoute
  AuthenticatedHostSpacesSpaceIdEditRoute: typeof AuthenticatedHostSpacesSpaceIdEditRoute
}

const AuthenticatedHostRouteChildren: AuthenticatedHostRouteChildren = {
  AuthenticatedHostBookingsRoute: AuthenticatedHostBookingsRoute,
  AuthenticatedHostEarningsRoute: AuthenticatedHostEarningsRoute,
  AuthenticatedHostIndexRoute: AuthenticatedHostIndexRoute,
  AuthenticatedHostMessagesBookingIdRoute:
    AuthenticatedHostMessagesBookingIdRoute,
  AuthenticatedHostPayoutsRefreshRoute: AuthenticatedHostPayoutsRefreshRoute,
  AuthenticatedHostPayoutsReturnRoute: AuthenticatedHostPayoutsReturnRoute,
  AuthenticatedHostRequestsRequestIdRoute:
    AuthenticatedHostRequestsRequestIdRoute,
  AuthenticatedHostSpacesNewRoute: AuthenticatedHostSpacesNewRoute,
  AuthenticatedHostMessagesIndexRoute: AuthenticatedHostMessagesIndexRoute,
  AuthenticatedHostSpacesIndexRoute: AuthenticatedHostSpacesIndexRoute,
  AuthenticatedHostSpacesSpaceIdEditRoute:
    AuthenticatedHostSpacesSpaceIdEditRoute,
}

const AuthenticatedHostRouteWithChildren =
  AuthenticatedHostRoute._addFileChildren(AuthenticatedHostRouteChildren)

interface AuthenticatedRenterRequestsRequestIdRouteChildren {
  AuthenticatedRenterRequestsRequestIdBookingRoute: typeof AuthenticatedRenterRequestsRequestIdBookingRoute
  AuthenticatedRenterRequestsRequestIdIndexRoute: typeof AuthenticatedRenterRequestsRequestIdIndexRoute
}

const AuthenticatedRenterRequestsRequestIdRouteChildren: AuthenticatedRenterRequestsRequestIdRouteChildren =
  {
    AuthenticatedRenterRequestsRequestIdBookingRoute:
      AuthenticatedRenterRequestsRequestIdBookingRoute,
    AuthenticatedRenterRequestsRequestIdIndexRoute:
      AuthenticatedRenterRequestsRequestIdIndexRoute,
  }

const AuthenticatedRenterRequestsRequestIdRouteWithChildren =
  AuthenticatedRenterRequestsRequestIdRoute._addFileChildren(
    AuthenticatedRenterRequestsRequestIdRouteChildren,
  )

interface AuthenticatedRenterRouteChildren {
  AuthenticatedRenterMatchesRoute: typeof AuthenticatedRenterMatchesRoute
  AuthenticatedRenterSearchRoute: typeof AuthenticatedRenterSearchRoute
  AuthenticatedRenterIndexRoute: typeof AuthenticatedRenterIndexRoute
  AuthenticatedRenterBookingsBookingIdRoute: typeof AuthenticatedRenterBookingsBookingIdRoute
  AuthenticatedRenterInventoryAddRoute: typeof AuthenticatedRenterInventoryAddRoute
  AuthenticatedRenterInventoryPhotosRoute: typeof AuthenticatedRenterInventoryPhotosRoute
  AuthenticatedRenterInventoryReviewRoute: typeof AuthenticatedRenterInventoryReviewRoute
  AuthenticatedRenterMessagesBookingIdRoute: typeof AuthenticatedRenterMessagesBookingIdRoute
  AuthenticatedRenterPaymentsReturnRoute: typeof AuthenticatedRenterPaymentsReturnRoute
  AuthenticatedRenterRequestsRequestIdRoute: typeof AuthenticatedRenterRequestsRequestIdRouteWithChildren
  AuthenticatedRenterRequestsNewRoute: typeof AuthenticatedRenterRequestsNewRoute
  AuthenticatedRenterBookingsIndexRoute: typeof AuthenticatedRenterBookingsIndexRoute
  AuthenticatedRenterInventoryIndexRoute: typeof AuthenticatedRenterInventoryIndexRoute
  AuthenticatedRenterMessagesIndexRoute: typeof AuthenticatedRenterMessagesIndexRoute
  AuthenticatedRenterRequestsIndexRoute: typeof AuthenticatedRenterRequestsIndexRoute
}

const AuthenticatedRenterRouteChildren: AuthenticatedRenterRouteChildren = {
  AuthenticatedRenterMatchesRoute: AuthenticatedRenterMatchesRoute,
  AuthenticatedRenterSearchRoute: AuthenticatedRenterSearchRoute,
  AuthenticatedRenterIndexRoute: AuthenticatedRenterIndexRoute,
  AuthenticatedRenterBookingsBookingIdRoute:
    AuthenticatedRenterBookingsBookingIdRoute,
  AuthenticatedRenterInventoryAddRoute: AuthenticatedRenterInventoryAddRoute,
  AuthenticatedRenterInventoryPhotosRoute:
    AuthenticatedRenterInventoryPhotosRoute,
  AuthenticatedRenterInventoryReviewRoute:
    AuthenticatedRenterInventoryReviewRoute,
  AuthenticatedRenterMessagesBookingIdRoute:
    AuthenticatedRenterMessagesBookingIdRoute,
  AuthenticatedRenterPaymentsReturnRoute:
    AuthenticatedRenterPaymentsReturnRoute,
  AuthenticatedRenterRequestsRequestIdRoute:
    AuthenticatedRenterRequestsRequestIdRouteWithChildren,
  AuthenticatedRenterRequestsNewRoute: AuthenticatedRenterRequestsNewRoute,
  AuthenticatedRenterBookingsIndexRoute: AuthenticatedRenterBookingsIndexRoute,
  AuthenticatedRenterInventoryIndexRoute:
    AuthenticatedRenterInventoryIndexRoute,
  AuthenticatedRenterMessagesIndexRoute: AuthenticatedRenterMessagesIndexRoute,
  AuthenticatedRenterRequestsIndexRoute: AuthenticatedRenterRequestsIndexRoute,
}

const AuthenticatedRenterRouteWithChildren =
  AuthenticatedRenterRoute._addFileChildren(AuthenticatedRenterRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedHostRoute: typeof AuthenticatedHostRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRenterRoute: typeof AuthenticatedRenterRouteWithChildren
  AuthenticatedAdminSupportCaseIdRoute: typeof AuthenticatedAdminSupportCaseIdRoute
  AuthenticatedSupportCasesCaseIdRoute: typeof AuthenticatedSupportCasesCaseIdRoute
  AuthenticatedAdminReviewsIndexRoute: typeof AuthenticatedAdminReviewsIndexRoute
  AuthenticatedAdminSupportIndexRoute: typeof AuthenticatedAdminSupportIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHostRoute: AuthenticatedHostRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRenterRoute: AuthenticatedRenterRouteWithChildren,
  AuthenticatedAdminSupportCaseIdRoute: AuthenticatedAdminSupportCaseIdRoute,
  AuthenticatedSupportCasesCaseIdRoute: AuthenticatedSupportCasesCaseIdRoute,
  AuthenticatedAdminReviewsIndexRoute: AuthenticatedAdminReviewsIndexRoute,
  AuthenticatedAdminSupportIndexRoute: AuthenticatedAdminSupportIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  FindStorageRoute: FindStorageRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GetStartedRoute: GetStartedRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListSpaceRoute: ListSpaceRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TrustRoute: TrustRoute,
  SpacesSpaceIdRoute: SpacesSpaceIdRoute,
  ApiPublicPayoutsReleaseRoute: ApiPublicPayoutsReleaseRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
