INSERT INTO public.storage_policy_versions (version, status, title, summary, sections,
  legal_review_required, effective_at, published_at)
VALUES (
  '1.0.0', 'published', 'Storage Policy',
  'What you can and can''t store through Project Stow, and the checks we run before a booking.',
  jsonb_build_array(
    jsonb_build_object('heading','Who this applies to',
      'body','This policy applies to everyone using Project Stow — renters storing belongings and hosts offering space. Hosts are letting a domestic space, not running a licensed storage facility.'),
    jsonb_build_object('heading','Items we never allow',
      'body','Fuel, gas cylinders and other compressed gases, explosives and fireworks, weapons and ammunition, controlled substances, biological or medical waste, live animals, and anything unlawful. These can''t be stored in a domestic space under any circumstances.'),
    jsonb_build_object('heading','Items that need extra care',
      'body','Household chemicals, batteries and other flammable goods, food and perishables, plants, liquids in bulk, medicines, cash, and irreplaceable documents are restricted. They may only be stored where the space is suitable and both people agree.'),
    jsonb_build_object('heading','Identifying what you''re storing',
      'body','Sealed or unmarked containers must be identified before a request can be sent. SpaceFit AI may suggest what it sees in your photos, but you decide and confirm what''s actually there.'),
    jsonb_build_object('heading','How checks work',
      'body','SpaceFit AI observes and proposes. You confirm or correct it. Our policy rules then decide, and the same rules are applied again on our servers when a request is sent. AI never decides whether something is lawful.'),
    jsonb_build_object('heading','Insurance and liability',
      'body','Project Stow is a marketplace, not an insurer. Checks and estimates reduce risk — they are not a guarantee of safety, security or cover. Arrange your own insurance for anything valuable.')
  ),
  false, now(), now()
);

WITH v AS (SELECT id FROM public.storage_policy_versions WHERE version = '1.0.0')
INSERT INTO public.storage_policy_rules (
  policy_version_id, rule_key, category, decision, severity,
  requires_user_confirmation, requires_staff_review,
  renter_message, host_message, internal_reason_code, required_space_attributes, sort_order)
SELECT v.id, d.rule_key, d.category, d.decision::public.policy_decision, d.severity,
       d.confirm, d.review, d.renter_message, d.host_message, d.reason,
       d.required_attrs::jsonb, d.sort_order
FROM v, (VALUES
  ('fuel','fuel','prohibited',5,false,false,
   'Fuel and flammable liquids can''t be stored in a domestic space. Please remove this item before requesting storage.',
   'Fuel is never allowed in a Project Stow space.','prohibited_fuel','{}',10),
  ('compressed_gas','compressed_gas','prohibited',5,false,false,
   'Gas cylinders and compressed gas can''t be stored in a domestic space.',
   'Compressed gas is never allowed.','prohibited_compressed_gas','{}',20),
  ('explosives','explosives','prohibited',5,false,false,
   'Fireworks, explosives and ammunition can''t be stored through Project Stow.',
   'Explosives are never allowed.','prohibited_explosives','{}',30),
  ('weapons','weapons','prohibited',5,false,false,
   'Weapons and firearms can''t be stored through Project Stow.',
   'Weapons are never allowed.','prohibited_weapons','{}',40),
  ('controlled_substances','controlled_substances','prohibited',5,false,false,
   'Controlled substances can''t be stored through Project Stow.',
   'Controlled substances are never allowed.','prohibited_controlled','{}',50),
  ('biological','biological','prohibited',5,false,false,
   'Medical or biological waste can''t be stored in a domestic space.',
   'Medical or biological waste is never allowed.','prohibited_biological','{}',60),
  ('animals','animals','prohibited',5,false,false,
   'Living things can''t be stored — please rehome or arrange care instead.',
   'Live animals are never allowed.','prohibited_animals','{}',70),
  ('waste','waste','prohibited',4,false,false,
   'Waste and refuse can''t be stored through Project Stow.',
   'Waste is never allowed.','prohibited_waste','{}',80),
  ('chemicals','chemicals','restricted',3,true,false,
   'Household chemicals need a dry, ventilated space and your host''s agreement. Confirm what this is before you continue.',
   'This renter has listed household chemicals.','restricted_chemicals','{"ventilation":"yes","damp_risk":"low"}',110),
  ('flammable','flammable','restricted',3,true,false,
   'Batteries and flammable goods need a dry, ventilated space and your host''s agreement.',
   'This renter has listed batteries or flammable goods.','restricted_flammable','{"ventilation":"yes"}',120),
  ('perishables','perishables','restricted',3,true,false,
   'Food and perishables aren''t suitable for most domestic storage. Confirm this is shelf-stable and sealed.',
   'This renter has listed food or perishables.','restricted_perishables','{"pest_risk":"low"}',130),
  ('plants','plants','restricted',2,true,false,
   'Plants and soil need light and air — confirm this is a dormant, dry item.',
   'This renter has listed plants or soil.','restricted_plants','{}',140),
  ('liquids','liquids','restricted',2,true,false,
   'Bulk liquids can leak. Confirm this is sealed and stored upright.',
   'This renter has listed bulk liquids.','restricted_liquids','{}',150),
  ('medicines','medicines','restricted',3,true,false,
   'Medicines should stay with you. Confirm this is sealed, in date and not temperature sensitive.',
   'This renter has listed medicines.','restricted_medicines','{"temperature_stable":"yes"}',160),
  ('cash_securities','cash_securities','restricted',4,true,false,
   'Cash and valuables aren''t covered and shouldn''t be stored. Confirm before continuing.',
   'This renter has listed cash or high-value securities.','restricted_cash','{"lockable":"yes"}',170),
  ('irreplaceable_documents','irreplaceable_documents','restricted',3,true,false,
   'Irreplaceable documents are best kept with you. Confirm before continuing.',
   'This renter has listed irreplaceable documents.','restricted_documents','{"damp_risk":"low","lockable":"yes"}',180),
  ('unidentified_container','unidentified_container','needs_identification',3,true,false,
   'Tell us what''s inside this container before you send a request.',
   'The renter is identifying a sealed container.','needs_identification_container','{}',200),
  ('electronics','electronics','allowed_with_confirmation',1,false,false,
   'Electronics store best somewhere dry and temperature stable.',
   'Electronics: dry, stable spaces work best.','allowed_electronics','{"damp_risk":"low"}',300),
  ('documents','documents','allowed_with_confirmation',1,false,false,
   'Paperwork stores best somewhere dry.','Paperwork: dry spaces work best.','allowed_documents','{"damp_risk":"low"}',310),
  ('bicycles','bicycles','allowed',0,false,false,
   'Bikes are fine to store.','','allowed_bicycles','{}',320),
  ('furniture','furniture','allowed',0,false,false,
   'Furniture is fine to store.','','allowed_furniture','{}',330),
  ('appliances','appliances','allowed',0,false,false,
   'Appliances are fine to store once drained and clean.','','allowed_appliances','{}',340),
  ('household','household','allowed',0,false,false,
   'Everyday household items are fine to store.','','allowed_household','{}',350)
) AS d(rule_key, category, decision, severity, confirm, review,
       renter_message, host_message, reason, required_attrs, sort_order);